### ISSUE TITLE
Implement cluster threshold

### ISSUE THREAD

**Issue by MSchnei** [MSchnei/morphViewer#4]
Aim is to remove unconnected voxels.

@ofgulban Could you push your cluster threshold script to the repository? Then I can integrate it with the button actions.

**Comment by ofgulban** [comment]
I have added the script.

**Comment by MSchnei** [comment]
Great, thanks!

**Comment by MSchnei** [comment]
This commit 4c0fc8315d7f43ecb47071c104552b3357b53e43 implements the first cluster threshold utility. It currently sets the connectivity to 2 and cluster size to 26.

In the future, these two values should be flexibly set. The best option for this seems to be a spin box widget for each of the two values, see here: https://www.tutorialspoint.com/pyqt/pyqt_qspinbox_widget.htm

**Comment by MSchnei** [comment]
or an input dialog widget:
https://www.tutorialspoint.com/pyqt/pyqt_qinputdialog_widget.htm

**Comment by MSchnei** [comment]
This commit 4af4486e57ecdd9b436861af09c21d58c4c71418 integrated sin boxes into the cluster threshold utility. Now the spin boxes can be used to set values for cluster size and connectivity and the cluster algorithms uses these values.

**Comment by MSchnei** [comment]
Although this is still in experimental mode, and exhaustive testing is still required, the feature is implemented and I therefore close the issue.

**Comment by ofgulban** [comment]
Great effort @MSchnei . I think this cluster thresholding script is quite slow in terms of speed. You might want to consider to optimize it further in the future.
